FROM python:3.10-slim

WORKDIR /app
COPY streamlit_app.py .
COPY requirements.txt .
COPY data_utilities/ ./data_utilities/
COPY dashboard_sections/ ./dashboard_sections/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]